# Generated by Django 6.0.1 on 2026-01-31 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
